### ISSUE TITLE
Blocker: we need some standardization

### ISSUE THREAD

**Issue by christina-de-martinez** [christina-de-martinez/babel-plugin-glowup-vibes#35]
There are tons of bussin ideas and PRs, you guys are 🐐 But a lot of the ideas conflict with each other. I opened a discussion so people can all have input on which ones should be merged. 

<https://github.com/christina-de-martinez/babel-plugin-glowup-vibes/discussions/37>

**Comment by Judge-Paul** [comment]
Hey have you created the discussion yet?

**Comment by christina-de-martinez** [comment]
Ha, I forgot GitHub has an actual tool for that. Here's an actual discussion: https://github.com/christina-de-martinez/babel-plugin-glowup-vibes/discussions/37

**Comment by Judge-Paul** [comment]
> Ha, I forgot GitHub has an actual tool for that. Here's an actual discussion: https://github.com/christina-de-martinez/babel-plugin-glowup-vibes/discussions/37

Also you should probably make a post on this since we all came from your Instagram

**Comment by christina-de-martinez** [comment]
Good idea, I might not have time today but I'll try to do a quick update soon.
