### ISSUE TITLE
Separate the object into its own JSON file

### ISSUE THREAD

**Issue by christina-de-martinez** [christina-de-martinez/babel-plugin-glowup-vibes#41]
separate the object into its own JSON file so that it's easier to track changes between the actual code and changes between the slang addition/changing.

Suggested by @stifskere - https://github.com/christina-de-martinez/babel-plugin-glowup-vibes/discussions/37#discussioncomment-7218716

**Comment by fastfists** [comment]
In our pr #8 we did exactly this

**Comment by christina-de-martinez** [comment]
This is fulfilled by https://github.com/christina-de-martinez/babel-plugin-glowup-vibes/pull/51 (which is really just PR #8 in a trenchcoat)
