### ISSUE TITLE
skrt -> break

### ISSUE THREAD

**Issue by christina-de-martinez** [christina-de-martinez/babel-plugin-glowup-vibes#52]
Idea from tyler_ai_specialist on Instagram

**Comment by kyanethmoran** [comment]
Hey :) awesome plugin btw! i saw this issue and it appears to have a conflict with the identifierMappings.js file already stating "PERIODT" is break. is this open issue a conflict or a change to the prexisting codebase?

**Comment by christina-de-martinez** [comment]
Hey, thanks! Great question. We can map multiple identifiers to the same thing, but not the other way around. So like, `PERIODT` could turn into `break` and `skrt` can also turn into `break`. (You can see that happening with `onGod` and `noCap`—they both transpile to `true`).
But we couldn't have `PERIODT` turn into both break and return. 
Let me know if that makes sense?
